"""crate table

Revision ID: c70415ff93f6
Revises: 
Create Date: 2020-04-06 22:35:44.060129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70415ff93f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=200), nullable=False, comment='case的名称'),
    sa.Column('desc', sa.String(length=200), nullable=True, comment='接口描述'),
    sa.Column('url', sa.String(length=800), nullable=False, comment='请求url'),
    sa.Column('methods', sa.String(length=30), nullable=False, comment='请求方式'),
    sa.Column('headers', sa.JSON(), nullable=True, comment='请求头信息'),
    sa.Column('variable_type', sa.String(length=32), nullable=True, comment='参数类型选择'),
    sa.Column('json', sa.JSON(), nullable=True, comment='请求body'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='variables'),
    sa.Column('validate', sa.JSON(), nullable=True, comment='validate'),
    sa.Column('extract', sa.JSON(), nullable=True, comment='extract'),
    sa.Column('setup_hooks', sa.JSON(), nullable=True, comment='setup_hooks'),
    sa.Column('teardown_hooks', sa.JSON(), nullable=True, comment='teardown_hooks'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suites_id', sa.Integer(), nullable=False, comment='testsuite id'),
    sa.Column('config_name', sa.String(length=200), nullable=False, comment='配置名称'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='测试组的描述'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='参数'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='测试组的状态0无效, 1有效'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('task_num', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.Integer(), nullable=False, comment='运行方式 1. 一次 2. 每天. 3.指定次数'),
    sa.Column('task_time', sa.JSON(), nullable=False, comment='运行时间'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='测试组的状态0无效, 1有效'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suites_id', sa.Integer(), nullable=False, comment='testsuite id'),
    sa.Column('case_name', sa.String(length=200), nullable=False, comment='case的名称'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='测试组的描述'),
    sa.Column('steps', sa.JSON(), nullable=True, comment='接口步骤'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='case的状态0无效, 1有效'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='测试组的描述'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('create_user', sa.String(length=40), nullable=True, comment='创建人'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='测试组的状态0无效, 1有效'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='所属testGroup'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='测试组的描述'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='测试组的状态0无效, 1有效'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_suites')
    op.drop_table('test_group')
    op.drop_table('test_cases')
    op.drop_table('task')
    op.drop_table('config')
    op.drop_table('api_info')
    # ### end Alembic commands ###
